{% set name = "trino" %}
{% set version = "0.313.0" %}

package:
  name: trino-python-client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trino-{{ version }}.tar.gz
  sha256: 5239a5d8cae55707d8c7b0a8e7ce264e7ab6ad6617f5a63c522ac6cbb3129e48

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pytz
    - requests

test:
  imports:
    - trino
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/trinodb/trino-python-client
  summary: Client for the Trino distributed SQL Engine
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Client for Trino (https://trino.io), a distributed SQL engine for
    interactive and batch big data processing. Provides a low-level client and
    a DBAPI 2.0 implementation.
  dev_url: https://github.com/trinodb/trino-python-client

extra:
  recipe-maintainers:
    - xylar
    - h-vetinari
  feedstock-name: trino
