{% set name = "trino" %}
{% set version = "0.336.0" %}

package:
  name: trino-python-client
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/trino-{{ version }}.tar.gz
  sha256: 389150841446949119c3c2c13c1a51bb4be1a27818e40ae40dd3701f36c02550

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - lz4
    - orjson >=3.11.0
    - python-dateutil
    - pytz
    - requests >=2.32.4
    - tzlocal
    - zstandard

test:
  imports:
    - trino
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/trinodb/trino-python-client
  summary: Client for the Trino distributed SQL Engine
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Client for Trino (https://trino.io), a distributed SQL engine for
    interactive and batch big data processing. Provides a low-level client and
    a DBAPI 2.0 implementation.
  dev_url: https://github.com/trinodb/trino-python-client

extra:
  recipe-maintainers:
    - xylar
    - h-vetinari
  feedstock-name: trino
