{% set name = "trino" %}
{% set version = "0.330.0" %}

package:
  name: trino-python-client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trino-{{ version }}.tar.gz
  sha256: 1e731be22bc6fb4ce6537287419c3d221faaa8d089f5a05b0f01ef25b860e96e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    # keep this for all python so we can stay noarch
    - backports.zoneinfo
    - python-dateutil
    - pytz
    - requests >=2.31.0
    - tzlocal

test:
  imports:
    - trino
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/trinodb/trino-python-client
  summary: Client for the Trino distributed SQL Engine
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Client for Trino (https://trino.io), a distributed SQL engine for
    interactive and batch big data processing. Provides a low-level client and
    a DBAPI 2.0 implementation.
  dev_url: https://github.com/trinodb/trino-python-client

extra:
  recipe-maintainers:
    - xylar
    - h-vetinari
  feedstock-name: trino
