{% set name = "trino" %}
{% set version = "0.315.0" %}

package:
  name: trino-python-client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trino-{{ version }}.tar.gz
  sha256: b10f40e9d178602b39463adb57c207a6c1803eb1a8ecb8cc9d5e710cf3dfbbc7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pytz
    - requests

test:
  imports:
    - trino
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/trinodb/trino-python-client
  summary: Client for the Trino distributed SQL Engine
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    Client for Trino (https://trino.io), a distributed SQL engine for
    interactive and batch big data processing. Provides a low-level client and
    a DBAPI 2.0 implementation.
  dev_url: https://github.com/trinodb/trino-python-client

extra:
  recipe-maintainers:
    - xylar
    - h-vetinari
  feedstock-name: trino
