{% set version = "0.310.0" %}

package:
  name: trino-python-client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/trino/trino-{{ version }}.tar.gz
  sha256: 7c0f332ffe185653316c275838411ee20e38d8716cb0d061b54ea8b870241fd7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - requests
    - six

test:
  imports:
    - trino

about:
  home: https://github.com/trinodb/trino-python-client
  license: Apache-2.0
  license_file: LICENSE
  summary: Python client for Trino
  description: |
    Client for Trino (https://trino.io), a distributed SQL engine for
    interactive and batch big data processing. Provides a low-level client and
    a DBAPI 2.0 implementation.
  dev_url: https://github.com/trinodb/trino-python-client

extra:
  recipe-maintainers:
    - h-vetinari
  feedstock-name: trino
